#welcome to the many imports
from discord.ext import commands
from discord import VoiceClient
from youtube_dl import YoutubeDL
from discord import VoiceChannel
import discord
from requests import get
import requests
from discord import FFmpegPCMAudio
from discord.ext import commands
from discord.utils import get
import asyncio
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from youtubesearchpython.__future__ import VideosSearch
import os
from dotenv import load_dotenv

#cog
class MusicCog(commands.Cog):

    def __init__(self, bot):
        load_dotenv("Tokens.env")
        self.bot = bot
        self.musicQ = []
        self.musicInfo = []
        self.client_id = os.getenv("SpotifyClientId")
        self.client_secret = os.getenv("SpotifyClientSecret")
        client_credentials_manager = SpotifyClientCredentials(client_id=self.client_id, client_secret=self.client_secret)
        self.sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)


    def search(self, query):
        with YoutubeDL({'format': 'bestaudio', 'noplaylist':'True'}) as ydl:
            try: requests.get(query)
            except: info = ydl.extract_info(f"ytsearch:{query}", download=False)['entries'][0]
            else: info = ydl.extract_info(query, download=False)
        return (info, info['formats'][0]['url'])

    # Hidden means it won't show up on the default help.
    @commands.command(name='join', hidden=False)
    async def join(self, ctx):
        voice = get(self.bot.voice_clients, guild=ctx.guild)
        channel = ctx.author.voice.channel

        if voice and voice.is_connected():
            await voice.move_to(channel)
        else:
            voice = await channel.connect()
        
    async def playsong(self, ctx, song):
        #Solves a problem I'll explain later
        FFMPEG_OPTS = {'before_options': '-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5', 'options': '-vn'}

        source = song
        vc = discord.utils.get(self.bot.voice_clients, guild=ctx.guild)

    # Check if the bot is already connected to a voice channel
        if vc and vc.is_connected():
            await vc.move_to(ctx.author.voice.channel)  # Move to the user's voice channel
        else:
            # Connect to the user's voice channel if not already connected
            channel = ctx.author.voice.channel
            vc = await channel.connect()

        vc.play(FFmpegPCMAudio(source, **FFMPEG_OPTS), after=lambda e: print('done', e))
    

    async def getSpotifySongs(self, ctx, playlist_url):
        results = self.sp.playlist_tracks(playlist_url)

        # Iterate over the playlist tracks
        for item in results['items']:
            track = item['track']
            track_name = track['name']
            artists = [artist['name'] for artist in track['artists']]
            searchresults = VideosSearch(f"{track_name} - {', '.join(artists)} auto generated by youtube", limit=1)
            videosResult = await searchresults.next()
            link = videosResult["result"][0]["link"]
            print(link)
            v,q = self.search(link)

            if(self.musicQ.__len__() <= 0):
                self.musicQ.append(q)
                self.musicInfo.append(v)
                await self.playsong(ctx, song=self.musicQ[0])
            else:
                self.musicInfo.append(v)
                self.musicQ.append(q)
                print(v["title"])


    @commands.command(name='play', hidden=False)
    async def play(self, ctx, *, query):

        if("open.spotify.com/playlist" in query):
           await self.getSpotifySongs(ctx, query)
        else:
            v,q = self.search(query)

            if(self.musicQ.__len__() <= 0):
                self.musicInfo.append(v)
                self.musicQ.append(q)
                await self.playsong(ctx, song=self.musicQ[0])
            else:
                self.musicInfo.append(v)
                self.musicQ.append(q)
                print(v["title"])
                await ctx.send(f"Added {v['title']} by, {v['author']}")


        while ctx.voice_client.is_playing():
            await asyncio.sleep(2)

        if(ctx.voice_client.is_playing()):
            print(ctx.voice_client.is_playing())
        else:
            self.musicInfo.pop(0)
            self.musicQ.pop(0)
            if(self.musicQ.__len__() >= 0):
                await self.playsong(ctx, self.musicQ[0])


    @commands.command(name='Queue', hidden=False)
    async def Queue(self, ctx):
        embed=discord.Embed(title="Music Queue", description=f"Next up: {self.musicInfo[1]['title']}", color=discord.Color(0x6257ff))
        thumbnail = self.musicInfo[1]["thumbnail"]
        print(self.musicInfo[1]["thumbnail"])
        embed.set_thumbnail(url=f"{thumbnail}")
        embed.set_author(name="Bought")
        #idk why I did it this way but it is the way it is
        [embed.add_field(name=x["title"], value=x["artist"], inline=True) for index, x in enumerate(self.musicInfo) if index != 0]     
        await ctx.send(embed=embed)
    
    @commands.command(name='skip', hidden=False)
    async def skip(self, ctx):
        ctx.voice_client.stop()

    @commands.command(name='pause', hidden=False)
    async def stop(self, ctx):
        ctx.voice_client.pause()
    
    @commands.command(name='resume', hidden=False)
    async def resume(self, ctx):
        ctx.voice_client.resume()
            


async def setup(bot):
    await bot.add_cog(MusicCog(bot))